# vim: set noet sw=4 ts=4:

__all__ = [
	'sql92_identchars',
	'sql92_namechars',
	'sql92_keywords',
	'sql99_identchars',
	'sql99_namechars',
	'sql99_keywords',
	'sql2003_identchars',
	'sql2003_namechars',
	'sql2003_keywords',
]

# Set of characters valid in unquoted identifiers in ANSI SQL-92. This is the
# list of characters used by the tokenizer to recognize an identifier in input
# text. Hence it should include lowercase characters.
# XXX Is this correct?

sql92_identchars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz_0123456789'

# Set of characters valid in unquoted names in ANSI SQL-92. This is the list of
# characters used by the parser to determine when to quote an object's name in
# output text. Hence it should NOT include lowercase characters.
# XXX Is this correct?

sql92_namechars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ_0123456789'

# Set of reserved keywords in ANSI SQL-92. Obtained from
# <http://developer.mimer.com/validator/sql-reserved-words.tml>

sql92_keywords = [
	'ABSOLUTE', 'ACTION', 'ADD', 'ALL', 'ALLOCATE', 'ALTER', 'AND', 'ANY',
	'ARE', 'AS', 'ASC', 'ASSERTION', 'AT', 'AUTHORIZATION', 'AVG', 'BEGIN',
	'BETWEEN', 'BIT', 'BIT_LENGTH', 'BOTH', 'BY', 'CALL', 'CASCADE',
	'CASCADED', 'CASE', 'CAST', 'CATALOG', 'CHAR', 'CHAR_LENGTH', 'CHARACTER',
	'CHARACTER_LENGTH', 'CHECK', 'CLOSE', 'COALESCE', 'COLLATE', 'COLLATION',
	'COLUMN', 'COMMIT', 'CONDITION', 'CONNECT', 'CONNECTION', 'CONSTRAINT',
	'CONSTRAINTS', 'CONTAINS', 'CONTINUE', 'CONVERT', 'CORRESPONDING', 'COUNT',
	'CREATE', 'CROSS', 'CURRENT', 'CURRENT_DATE', 'CURRENT_PATH',
	'CURRENT_TIME', 'CURRENT_TIMESTAMP', 'CURRENT_USER', 'CURSOR', 'DATE',
	'DAY', 'DEALLOCATE', 'DEC', 'DECIMAL', 'DECLARE', 'DEFAULT', 'DEFERRABLE',
	'DEFERRED', 'DELETE', 'DESC', 'DESCRIBE', 'DESCRIPTOR', 'DETERMINISTIC',
	'DIAGNOSTICS', 'DISCONNECT', 'DISTINCT', 'DO', 'DOMAIN', 'DOUBLE', 'DROP',
	'ELSE', 'ELSEIF', 'END', 'ESCAPE', 'EXCEPT', 'EXCEPTION', 'EXEC',
	'EXECUTE', 'EXISTS', 'EXIT', 'EXTERNAL', 'EXTRACT', 'FALSE', 'FETCH',
	'FIRST', 'FLOAT', 'FOR', 'FOREIGN', 'FOUND', 'FROM', 'FULL', 'FUNCTION',
	'GET', 'GLOBAL', 'GO', 'GOTO', 'GRANT', 'GROUP', 'HANDLER', 'HAVING',
	'HOUR', 'IDENTITY', 'IF', 'IMMEDIATE', 'IN', 'INDICATOR', 'INITIALLY',
	'INNER', 'INOUT', 'INPUT', 'INSENSITIVE', 'INSERT', 'INT', 'INTEGER',
	'INTERSECT', 'INTERVAL', 'INTO', 'IS', 'ISOLATION', 'JOIN', 'KEY',
	'LANGUAGE', 'LAST', 'LEADING', 'LEAVE', 'LEFT', 'LEVEL', 'LIKE', 'LOCAL',
	'LOOP', 'LOWER', 'MATCH', 'MAX', 'MIN', 'MINUTE', 'MODULE', 'MONTH',
	'NAMES', 'NATIONAL', 'NATURAL', 'NCHAR', 'NEXT', 'NO', 'NOT', 'NULL',
	'NULLIF', 'NUMERIC', 'OCTET_LENGTH', 'OF', 'ON', 'ONLY', 'OPEN', 'OPTION',
	'OR', 'ORDER', 'OUT', 'OUTER', 'OUTPUT', 'OVERLAPS', 'PAD', 'PARAMETER',
	'PARTIAL', 'PATH', 'POSITION', 'PRECISION', 'PREPARE', 'PRESERVE',
	'PRIMARY', 'PRIOR', 'PRIVILEGES', 'PROCEDURE', 'PUBLIC', 'READ', 'REAL',
	'REFERENCES', 'RELATIVE', 'REPEAT', 'RESIGNAL', 'RESTRICT', 'RETURN',
	'RETURNS', 'REVOKE', 'RIGHT', 'ROLLBACK', 'ROUTINE', 'ROWS', 'SCHEMA',
	'SCROLL', 'SECOND', 'SECTION', 'SELECT', 'SESSION', 'SESSION_USER', 'SET',
	'SIGNAL', 'SIZE', 'SMALLINT', 'SOME', 'SPACE', 'SPECIFIC', 'SQL',
	'SQLCODE', 'SQLERROR', 'SQLEXCEPTION', 'SQLSTATE', 'SQLWARNING',
	'SUBSTRING', 'SUM', 'SYSTEM_USER', 'TABLE', 'TEMPORARY', 'THEN', 'TIME',
	'TIMESTAMP', 'TIMEZONE_HOUR', 'TIMEZONE_MINUTE', 'TO', 'TRAILING',
	'TRANSACTION', 'TRANSLATE', 'TRANSLATION', 'TRIM', 'TRUE', 'UNDO', 'UNION',
	'UNIQUE', 'UNKNOWN', 'UNTIL', 'UPDATE', 'UPPER', 'USAGE', 'USER', 'USING',
	'VALUE', 'VALUES', 'VARCHAR', 'VARYING', 'VIEW', 'WHEN', 'WHENEVER',
	'WHERE', 'WHILE', 'WITH', 'WORK', 'WRITE', 'YEAR', 'ZONE',
]

# Set of characters valid in unquoted identifiers and names in ANSI SQL-99 (see
# above)
# XXX Is this correct?

sql99_identchars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz_0123456789'
sql99_namechars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ_0123456789'

# Set of reserved keywords in ANSI SQL-99. Obtained from
# <http://developer.mimer.com/validator/sql-reserved-words.tml>

sql99_keywords = [
	'ABSOLUTE', 'ACTION', 'ADD', 'AFTER', 'ALL', 'ALLOCATE', 'ALTER', 'AND',
	'ANY', 'ARE', 'ARRAY', 'AS', 'ASC', 'ASENSITIVE', 'ASSERTION',
	'ASYMMETRIC', 'AT', 'ATOMIC', 'AUTHORIZATION', 'BEFORE', 'BEGIN',
	'BETWEEN', 'BINARY', 'BIT', 'BLOB', 'BOOLEAN', 'BOTH', 'BREADTH', 'BY',
	'CALL', 'CALLED', 'CASCADE', 'CASCADED', 'CASE', 'CAST', 'CATALOG', 'CHAR',
	'CHARACTER', 'CHECK', 'CLOB', 'CLOSE', 'COLLATE', 'COLLATION', 'COLUMN',
	'COMMIT', 'CONDITION', 'CONNECT', 'CONNECTION', 'CONSTRAINT',
	'CONSTRAINTS', 'CONSTRUCTOR', 'CONTINUE', 'CORRESPONDING', 'CREATE',
	'CROSS', 'CUBE', 'CURRENT', 'CURRENT_DATE',
	'CURRENT_DEFAULT_TRANSFORM_GROUP', 'CURRENT_PATH', 'CURRENT_ROLE',
	'CURRENT_TIME', 'CURRENT_TIMESTAMP', 'CURRENT_TRANSFORM_GROUP_FOR_TYPE',
	'CURRENT_USER', 'CURSOR', 'CYCLE', 'DATA', 'DATE', 'DAY', 'DEALLOCATE',
	'DEC', 'DECIMAL', 'DECLARE', 'DEFAULT', 'DEFERRABLE', 'DEFERRED', 'DELETE',
	'DEPTH', 'DEREF', 'DESC', 'DESCRIBE', 'DESCRIPTOR', 'DETERMINISTIC',
	'DIAGNOSTICS', 'DISCONNECT', 'DISTINCT', 'DO', 'DOMAIN', 'DOUBLE', 'DROP',
	'DYNAMIC', 'EACH', 'ELSE', 'ELSEIF', 'END', 'EQUALS', 'ESCAPE', 'EXCEPT',
	'EXCEPTION', 'EXEC', 'EXECUTE', 'EXISTS', 'EXIT', 'EXTERNAL', 'FALSE',
	'FETCH', 'FILTER', 'FIRST', 'FLOAT', 'FOR', 'FOREIGN', 'FOUND', 'FREE',
	'FROM', 'FULL', 'FUNCTION', 'GENERAL', 'GET', 'GLOBAL', 'GO', 'GOTO',
	'GRANT', 'GROUP', 'GROUPING', 'HANDLER', 'HAVING', 'HOLD', 'HOUR',
	'IDENTITY', 'IF', 'IMMEDIATE', 'IN', 'INDICATOR', 'INITIALLY', 'INNER',
	'INOUT', 'INPUT', 'INSENSITIVE', 'INSERT', 'INT', 'INTEGER', 'INTERSECT',
	'INTERVAL', 'INTO', 'IS', 'ISOLATION', 'ITERATE', 'JOIN', 'KEY',
	'LANGUAGE', 'LARGE', 'LAST', 'LATERAL', 'LEADING', 'LEAVE', 'LEFT',
	'LEVEL', 'LIKE', 'LOCAL', 'LOCALTIME', 'LOCALTIMESTAMP', 'LOCATOR', 'LOOP',
	'MAP', 'MATCH', 'METHOD', 'MINUTE', 'MODIFIES', 'MODULE', 'MONTH', 'NAMES',
	'NATIONAL', 'NATURAL', 'NCHAR', 'NCLOB', 'NEW', 'NEXT', 'NO', 'NONE',
	'NOT', 'NULL', 'NUMERIC', 'OBJECT', 'OF', 'OLD', 'ON', 'ONLY', 'OPEN',
	'OPTION', 'OR', 'ORDER', 'ORDINALITY', 'OUT', 'OUTER', 'OUTPUT', 'OVER',
	'OVERLAPS', 'PAD', 'PARAMETER', 'PARTIAL', 'PARTITION', 'PATH',
	'PRECISION', 'PREPARE', 'PRESERVE', 'PRIMARY', 'PRIOR', 'PRIVILEGES',
	'PROCEDURE', 'PUBLIC', 'RANGE', 'READ', 'READS', 'REAL', 'RECURSIVE',
	'REF', 'REFERENCES', 'REFERENCING', 'RELATIVE', 'RELEASE', 'REPEAT',
	'RESIGNAL', 'RESTRICT', 'RESULT', 'RETURN', 'RETURNS', 'REVOKE', 'RIGHT',
	'ROLE', 'ROLLBACK', 'ROLLUP', 'ROUTINE', 'ROW', 'ROWS', 'SAVEPOINT',
	'SCHEMA', 'SCOPE', 'SCROLL', 'SEARCH', 'SECOND', 'SECTION', 'SELECT',
	'SENSITIVE', 'SESSION', 'SESSION_USER', 'SET', 'SETS', 'SIGNAL', 'SIMILAR',
	'SIZE', 'SMALLINT', 'SOME', 'SPACE', 'SPECIFIC', 'SPECIFICTYPE', 'SQL',
	'SQLEXCEPTION', 'SQLSTATE', 'SQLWARNING', 'START', 'STATE', 'STATIC',
	'SYMMETRIC', 'SYSTEM', 'SYSTEM_USER', 'TABLE', 'TEMPORARY', 'THEN', 'TIME',
	'TIMESTAMP', 'TIMEZONE_HOUR', 'TIMEZONE_MINUTE', 'TO', 'TRAILING',
	'TRANSACTION', 'TRANSLATION', 'TREAT', 'TRIGGER', 'TRUE', 'UNDER', 'UNDO',
	'UNION', 'UNIQUE', 'UNKNOWN', 'UNNEST', 'UNTIL', 'UPDATE', 'USAGE', 'USER',
	'USING', 'VALUE', 'VALUES', 'VARCHAR', 'VARYING', 'VIEW', 'WHEN',
	'WHENEVER', 'WHERE', 'WHILE', 'WINDOW', 'WITH', 'WITHIN', 'WITHOUT',
	'WORK', 'WRITE', 'YEAR', 'ZONE',
]

# Set of characters valid in unquoted identifiers and names in ANSI SQL-2003
# (see above)
# XXX Is this correct?

sql2003_identchars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz_0123456789'
sql2003_namechars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ_0123456789'

# Set of reserved keywords in ANSI SQL-2003. Obtained from
# <http://developer.mimer.com/validator/sql-reserved-words.tml>

sql2003_keywords = [
	'ADD', 'ALL', 'ALLOCATE', 'ALTER', 'AND', 'ANY', 'ARE', 'ARRAY', 'AS',
	'ASENSITIVE', 'ASYMMETRIC', 'AT', 'ATOMIC', 'AUTHORIZATION', 'BEGIN',
	'BETWEEN', 'BIGINT', 'BINARY', 'BLOB', 'BOOLEAN', 'BOTH', 'BY', 'CALL',
	'CALLED', 'CASCADED', 'CASE', 'CAST', 'CHAR', 'CHARACTER', 'CHECK', 'CLOB',
	'CLOSE', 'COLLATE', 'COLUMN', 'COMMIT', 'CONDITION', 'CONNECT',
	'CONSTRAINT', 'CONTINUE', 'CORRESPONDING', 'CREATE', 'CROSS', 'CUBE',
	'CURRENT', 'CURRENT_DATE', 'CURRENT_DEFAULT_TRANSFORM_GROUP',
	'CURRENT_PATH', 'CURRENT_ROLE', 'CURRENT_TIME', 'CURRENT_TIMESTAMP',
	'CURRENT_TRANSFORM_GROUP_FOR_TYPE', 'CURRENT_USER', 'CURSOR', 'CYCLE',
	'DATE', 'DAY', 'DEALLOCATE', 'DEC', 'DECIMAL', 'DECLARE', 'DEFAULT',
	'DELETE', 'DEREF', 'DESCRIBE', 'DETERMINISTIC', 'DISCONNECT', 'DISTINCT',
	'DO', 'DOUBLE', 'DROP', 'DYNAMIC', 'EACH', 'ELEMENT', 'ELSE', 'ELSEIF',
	'END', 'ESCAPE', 'EXCEPT', 'EXEC', 'EXECUTE', 'EXISTS', 'EXIT', 'EXTERNAL',
	'FALSE', 'FETCH', 'FILTER', 'FLOAT', 'FOR', 'FOREIGN', 'FREE', 'FROM',
	'FULL', 'FUNCTION', 'GET', 'GLOBAL', 'GRANT', 'GROUP', 'GROUPING',
	'HANDLER', 'HAVING', 'HOLD', 'HOUR', 'IDENTITY', 'IF', 'IMMEDIATE', 'IN',
	'INDICATOR', 'INNER', 'INOUT', 'INPUT', 'INSENSITIVE', 'INSERT', 'INT',
	'INTEGER', 'INTERSECT', 'INTERVAL', 'INTO', 'IS', 'ITERATE', 'JOIN',
	'LANGUAGE', 'LARGE', 'LATERAL', 'LEADING', 'LEAVE', 'LEFT', 'LIKE',
	'LOCAL', 'LOCALTIME', 'LOCALTIMESTAMP', 'LOOP', 'MATCH', 'MEMBER', 'MERGE',
	'METHOD', 'MINUTE', 'MODIFIES', 'MODULE', 'MONTH', 'MULTISET', 'NATIONAL',
	'NATURAL', 'NCHAR', 'NCLOB', 'NEW', 'NO', 'NONE', 'NOT', 'NULL', 'NUMERIC',
	'OF', 'OLD', 'ON', 'ONLY', 'OPEN', 'OR', 'ORDER', 'OUT', 'OUTER', 'OUTPUT',
	'OVER', 'OVERLAPS', 'PARAMETER', 'PARTITION', 'PRECISION', 'PREPARE',
	'PRIMARY', 'PROCEDURE', 'RANGE', 'READS', 'REAL', 'RECURSIVE', 'REF',
	'REFERENCES', 'REFERENCING', 'RELEASE', 'REPEAT', 'RESIGNAL', 'RESULT',
	'RETURN', 'RETURNS', 'REVOKE', 'RIGHT', 'ROLLBACK', 'ROLLUP', 'ROW',
	'ROWS', 'SAVEPOINT', 'SCOPE', 'SCROLL', 'SEARCH', 'SECOND', 'SELECT',
	'SENSITIVE', 'SESSION_USER', 'SET', 'SIGNAL', 'SIMILAR', 'SMALLINT',
	'SOME', 'SPECIFIC', 'SPECIFICTYPE', 'SQL', 'SQLEXCEPTION', 'SQLSTATE',
	'SQLWARNING', 'START', 'STATIC', 'SUBMULTISET', 'SYMMETRIC', 'SYSTEM',
	'SYSTEM_USER', 'TABLE', 'TABLESAMPLE', 'THEN', 'TIME', 'TIMESTAMP',
	'TIMEZONE_HOUR', 'TIMEZONE_MINUTE', 'TO', 'TRAILING', 'TRANSLATION',
	'TREAT', 'TRIGGER', 'TRUE', 'UNDO', 'UNION', 'UNIQUE', 'UNKNOWN', 'UNNEST',
	'UNTIL', 'UPDATE', 'USER', 'USING', 'VALUE', 'VALUES', 'VARCHAR',
	'VARYING', 'WHEN', 'WHENEVER', 'WHERE', 'WHILE', 'WINDOW', 'WITH',
	'WITHIN', 'WITHOUT', 'YEAR',
]
